server:
  port: 5010

spring:
  application:
    name: GATEWAY-SERVICE

  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri:
            lb://USER-SERVICE
          predicates:
            - Path=/auth/**, /users/**, /api/users/**, /

        - id: TASK-SERVICE
          uri:
            lb://TASK-SERVICE
          predicates:
            - Path=/api/tasks/**, /tasks/**

        - id: SUBMISSION-SERVICE
          uri:
            lb://SUBMISSION-SERVICE
          predicates:
            - Path=/api/submissions/**, /submissions/**



      default-filters:
          - DedupeResponseHeader=Access-Control-Allow-Credentials
          - DedupeResponseHeader=Access-Control-Allow-Origin

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"



eureka:
  instance:
    prefer-ip-address: true
    leaseRenewalIntervalInSeconds: 30 # Adjust renewal interval as needed
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:5005/eureka/
    registry-fetch-interval-seconds: 10 # Adjust fetch interval as needed
