server:
  port: 5000

# mysql database configuration
spring:
  application:
    name: USER-SERVICE
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/task_management_system
    username: root
    password: '@purnaale#1633'
    driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  instance:
    prefer-ip-address: true
    leaseRenewalIntervalInSeconds: 30 # Adjust renewal interval as needed
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:5005/eureka/
    registry-fetch-interval-seconds: 10 # Adjust fetch interval as needed
